apiVersion: v2
appVersion: v1.0.0
kubeVersion: ">=1.25.0-0"
description: A Helm chart to deploy Prometheus using ArgoCD
name: prometheus
version: 1.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 67.9.0
    repository: https://prometheus-community.github.io/helm-charts
