kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      hosts:
        - grafana-3.local  
    persistence:
      enabled: true
      type: sts
      storageClassName: "openebs-lvm"
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      finalizers:
        - kubernetes.io/pvc-protection
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "openebs-lvm"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 25Gi