apiVersion: v2
appVersion: v1.0.0
kubeVersion: ">=1.25.0-0"
description: A Helm chart to deploy ClickHouse Operator using ArgoCD
name: clickhouse-operator
version: 1.0.0
dependencies:
  - name: altinity-clickhouse-operator 
    version: 0.24.0
    repository: https://docs.altinity.com/clickhouse-operator/
