
pulsar:

  volumes:
    persistence: true

  # disabled AntiAffinity
  affinity:
    anti_affinity: false

  # disable auto recovery
  components:
    autorecovery: false
    pulsar_manager: true
    proxy: true

  zookeeper:
    replicaCount: 1
    volumes:
      data:
        size: 5Gi
        storageClassName: openebs-lvm

  bookkeeper:
    replicaCount: 3
    volumes:
      common:
        size: 10Gi
        storageClassName: openebs-lvm
    configData:
      # minimal memory use for bookkeeper
      # https://bookkeeper.apache.org/docs/reference/config#db-ledger-storage-settings
      dbStorage_writeCacheMaxSizeMb: "32"
      dbStorage_readAheadCacheMaxSizeMb: "32"
      dbStorage_rocksDB_writeBufferSizeMB: "8"
      dbStorage_rocksDB_blockCacheSize: "8388608"

  broker:
    replicaCount: 3
    configData:
      ## Enable `autoSkipNonRecoverableData` since bookkeeper is running
      ## without persistence
      autoSkipNonRecoverableData: "true"

  proxy:
    replicaCount: 1

  pulsar_manager:
    volumes:
      data:
        size: 512Mi
        storageClassName: openebs-lvm

  ## enable monitoring stack
  kube-prometheus-stack:
    enabled: true
    prometheusOperator:
      enabled: false
    grafana:
      enabled: true
    alertmanager:
      enabled: false
    prometheus:
      enabled: true    