apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          bootstrap:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-simple-bootstrap.local.
              external-dns.alpha.kubernetes.io/ttl: "60"
            host: kafka-simple-bootstrap.local
          brokers:
            - broker: 0
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-simple-broker-0.local.
                external-dns.alpha.kubernetes.io/ttl: "60"
              host: kafka-simple-broker-0.local
            - broker: 1
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-simple-broker-1.local.
                external-dns.alpha.kubernetes.io/ttl: "60"
              host: kafka-simple-broker-1.local
            - broker: 2
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-simple-broker-2.local.
                external-dns.alpha.kubernetes.io/ttl: "60"
              host: kafka-simple-broker-2.local
          brokerCertChainAndKey:
            secretName: my-cluster-certificate
            certificate: tls.crt
            key: tls.key                
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
        class: openebs-lvm
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
      class: openebs-lvm
  entityOperator:
    topicOperator: {}
    userOperator: {}